import { defineConfig } from "tsup";

const OUT_DIR = "dist";

export default defineConfig([
	// ESM build
	{
		entry: ["src/index.ts"],
		format: ["esm"],
		dts: true,
		sourcemap: true,
		outDir: OUT_DIR,
		clean: true,
		target: "es2020",
		outExtension: () => ({ js: ".mjs", dts: ".d.ts" }),
	},
	// CJS build
	{
		entry: ["src/index.ts"],
		format: ["cjs"],
		dts: false, // already generated by esm build
		sourcemap: true,
		outDir: OUT_DIR,
		clean: false,
		target: "es2020",
		outExtension: () => ({ js: ".cjs" }),
	},
	// Browser build (UMD)
	{
		entry: ["src/index.ts"],
		format: ["iife"],
		globalName: "ApfelSequence",
		dts: false,
		sourcemap: true,
		outDir: OUT_DIR,
		clean: false,
		target: "es2020",
		outExtension: () => ({ js: ".browser.js" }),
	},
]);
